name: legate-core-test
channels:
  - conda-forge
dependencies:
  - python=3.8

  # build
  - git
  - nccl
  - make
  - zlib
  - cmake
  - ninja
  - c-compiler
  - cxx-compiler
  - setuptools>=60
  - scikit-build>=0.13.1

  # runtime
  - cffi
  - numpy>=1.22
  - opt_einsum
  - pyarrow>=5
  - scipy
  - typing_extensions
  - llvm-openmp

  # tests
  - clang>=8
  - clang-tools>=8
  - colorama
  - coverage
  - mock
  - mypy>=0.961
  - pre-commit
  - pynvml
  - pytest
  - pytest-cov
  - pytest-mock
  - types-docutils

  # pip dependencies
  - pip
  - pip:
    # docs
    - jinja2
    - pydata-sphinx-theme
    - recommonmark
    - sphinx>=4.4.0
    - sphinx-copybutton
    - sphinx-markdown-tables

    # examples
    - tifffile
